#!/usr/bin/env bash
# ============================================================================
# deploy-keys.sh — generate secrets for .env.prod (prod compose stack)
#
# Uses:
#   ./deploy-keys.sh                 write .env.prod (refuses if it exists)
#   ./deploy-keys.sh --force         overwrite .env.prod
#   ./deploy-keys.sh --out FILE      write to FILE instead
#   SITE_URL=https://feria.example.com ./deploy-keys.sh
#
# Requires: openssl, node. Never prints secrets to logs beyond the file.
# ============================================================================
set -euo pipefail

OUT=".env.prod"
FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --out) OUT="${2:?--out needs a path}"; shift 2 ;;
    --out=*) OUT="${1#--out=}"; shift ;;
    -h|--help) sed -n '2,/^# ===/p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1 (try --help)" >&2; exit 1 ;;
  esac
done

if [ -e "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "✗ $OUT exists. Re-run with --force to overwrite." >&2
  exit 1
fi

for cmd in openssl node; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "✗ missing '$cmd'" >&2; exit 1; }
done

SITE_URL="${SITE_URL:-https://feria.example.com}"
GATEWAY_PORT="${GATEWAY_PORT:-8080}"

POSTGRES_PASSWORD="$(openssl rand -hex 24)"   # alnum only: embedded in URLs
JWT_SECRET="$(openssl rand -hex 32)"          # 64 hex chars
SECRET_KEY_BASE="$(openssl rand -base64 48)"  # >= 64 chars (realtime)
REALTIME_DB_ENC_KEY="$(openssl rand -hex 8)"  # exactly 16 chars (realtime)

# HS256 legacy API keys, same shape as dev.sh anon key (role/iss/iat/exp).
read -r ANON_KEY SERVICE_ROLE_KEY < <(JWT_SECRET="$JWT_SECRET" node --input-type=module -e '
import crypto from "node:crypto";
const s = process.env.JWT_SECRET;
const mk = (role) => {
  const b64 = (b) => Buffer.from(b).toString("base64url");
  const h = b64(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const now = Math.floor(Date.now() / 1000);
  const p = b64(JSON.stringify({ role, iss: "supabase", iat: now, exp: now + 315360000 }));
  return h + "." + p + "." + crypto.createHmac("sha256", s).update(h + "." + p).digest("base64url");
};
console.log(mk("anon") + " " + mk("service_role"));
')

umask 077
cat > "$OUT" <<ENV
# Generated by ./deploy-keys.sh on $(date -u +%FT%TZ). Do not commit.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
SECRET_KEY_BASE=$SECRET_KEY_BASE
REALTIME_DB_ENC_KEY=$REALTIME_DB_ENC_KEY
VITE_SUPABASE_URL=$SITE_URL
GATEWAY_PORT=$GATEWAY_PORT
ENV
chmod 600 "$OUT"

echo "✓ wrote $OUT (mode 600). Next:"
echo "  docker compose --env-file $OUT up -d --build"
